version: "2.4"

services:
  yc_billing:
    container_name: yc_billing
    build: .
    image: yc_billing:dev
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
